### ISSUE TITLE
好像和配置项不吻合

### ISSUE THREAD

**Issue by youwenbo** [ruilisi/go-pangu#2]
https://github.com/ruilisi/go-pangu/blob/5b790838420d7f8116a49bef45d42380bae0db12/db/db.go#L40
我配置是这样的：DATABASE_URL: postgres://test_user:123456@localhost:5432/go_pangu_development?sslmode=disable
运行后提示这个错，调试了很久跑步起来，感觉有问题，帮忙看下啥原因
2020/12/30 18:03:33 /home/go-pangu/db/db.go:40
[error] failed to initialize database, got error failed to connect to `host=localhost user=test_user database=`: server error (致命错误: 数据库 "test_user" 不存在 (SQLSTATE 3D000))
panic: failed to connect to `host=localhost user=test_user database=`: server error (致命错误: 数据库 "test_user" 不存在 (SQLSTATE 3D000))

**Comment by hophacker** [comment]
我们看一下

**Comment by ExcitingFrog** [comment]
这里的 test_user 应该是用户名  
你在命令行可以使用 

sudo -i -u test_user  切换到此用户
psql  进入数据库

来验证是否正常

**Comment by youwenbo** [comment]
> 这里的 test_user 应该是用户名
> 你在命令行可以使用
> 
> sudo -i -u test_user 切换到此用户
> psql 进入数据库
> 
> 来验证是否正常

test_user 是用户名，但运行后把这个读成了数据库名了 -----------致命错误: 数据库 "test_user" 不存在 (SQLSTATE 3D000))

**Comment by ExcitingFrog** [comment]
> > 这里的 test_user 应该是用户名
> > 你在命令行可以使用
> > sudo -i -u test_user 切换到此用户
> > psql 进入数据库
> > 来验证是否正常
> 
> test_user 是用户名，但运行后把这个读成了数据库名了 -----------致命错误: 数据库 "test_user" 不存在 (SQLSTATE 3D000))

你好 请问你是否运行过 go run main.go -db=create  这个命令来创建数据库

**Comment by ExcitingFrog** [comment]
可以把application.yml全部复制过来吗

**Comment by youwenbo** [comment]
就是 go run main.go -db=create的时候报的错，配置如下，就改了PG的用户名密码
DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
HTTP_PORT: 3002
BASE_DATABASE_URL: postgres://test_user:123456@localhost:5432
DATABASE_URL: postgres://test_user:123456@localhost:5432/go_pangu_development?sslmode=disable
DATABASE_TESTURL: postgres://test_user:123456@localhost:5432/go_pangu_test?sslmode=disable
REDIS_URL: redis://:123456@localhost:6379/7
WORKERS: CollectIpWorker,QcloudSmsWorker
SMS_APPID:  
SMS_APPKEY: 
SMS_TEMPID: 
SMS_APPLYTEMPID: 
ALIPAY_APP_ID: 
ALIPAY_PRIVATE_KEY: 
ALIPAY_PUBLIC_KEY: 
ALIPAY_URL: 
INFLUXDB_DB: go_pangu
INFLUXDB_HOST: localhost
INFLUXDB_PORT: '8086'

**Comment by ExcitingFrog** [comment]
> 就是 go run main.go -db=create的时候报的错，配置如下，就改了PG的用户名密码
> DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
> HTTP_PORT: 3002
> BASE_DATABASE_URL: postgres://test_user:123456@localhost:5432
> DATABASE_URL: postgres://test_user:123456@localhost:5432/go_pangu_development?sslmode=disable
> DATABASE_TESTURL: postgres://test_user:123456@localhost:5432/go_pangu_test?sslmode=disable
> REDIS_URL: redis://:123456@localhost:6379/7
> WORKERS: CollectIpWorker,QcloudSmsWorker
> SMS_APPID:
> SMS_APPKEY:
> SMS_TEMPID:
> SMS_APPLYTEMPID:
> ALIPAY_APP_ID:
> ALIPAY_PRIVATE_KEY:
> ALIPAY_PUBLIC_KEY:
> ALIPAY_URL:
> INFLUXDB_DB: go_pangu
> INFLUXDB_HOST: localhost
> INFLUXDB_PORT: '8086'

查清楚了 是数据库用户问题

先用postgres用户进入数据库
sudo -i -u postgres
psql 

接着创建test_user用户
CREATE USER test_user WITH PASSWORD '123456' superuser;
接着创建一个test_user的数据库
create database test_user;


注：
配置里的DATABASE_TESTURL  使用的go_pangu_test暂时不能修改

运行go run main.go -db=create
进入test文件夹 运行 ginkgo  看是否全部测试成功

**Comment by youwenbo** [comment]
我直接使用postgres，不使用test_user试了下好了。但我之前用过postgres用户试过也不行，不知道为啥现在又好了。
先这样了，谢谢了
